---
image: node:14.16-alpine # image par défaut

stages:
- build
- test
- deploy staging
- deploy production
- production tests

variables:
  STAGING_DOMAIN: luminess-chris-demo-react-staging.surge.sh
  PRODUCTION_DOMAIN: luminess-chris-demo-react.surge.sh

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules

build website:
  stage: build
  script:
  - npm install
  - npm run build
  artifacts:
    paths:
    - ./build

test artifact:
  stage: test
  image: alpine
  script:
  - grep -q "React" ./build/index.html

test website:
  stage: test
  before_script:
  - apk add --no-cache curl
  script:
  #- npm install
  - npm run start &
  - sleep 30
  - curl -Is localhost:3000 | head -n 1 | grep "OK"
  
deploy staging:
  stage: deploy staging
  environment:
    name: staging
    url: https://$STAGING_DOMAIN
  only:
  - features
  script:
  - npm install -g surge
  - surge --project ./build --domain $STAGING_DOMAIN

deploy production:
  stage: deploy production
  environment:
    name: production
    url: https://$PRODUCTION_DOMAIN
  only:
  - master
  script:
  - npm install -g surge
  - surge --project ./build --domain $PRODUCTION_DOMAIN
  when: manual

production tests:
  image: alpine
  stage: production tests
  only:
  - master
  before_script:
  - apk add --no-cache curl
  script:
  - curl -Is https://$PRODUCTION_DOMAIN | head -n 1 | grep "OK"
  - curl -s https://$PRODUCTION_DOMAIN | grep "React"