---
image: node:14.16-alpine # image par défaut

stages:
- build
- test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules

build website:
  stage: build
  script:
  - npm install
  - npm run build
  artifacts:
    paths:
    - ./build

test artifact:
  stage: test
  image: alpine
  script:
  - grep -q "React" ./build/index.html

test website:
  stage: test
  before_script:
  - apk add --no-cache curl
  script:
  #- npm install
  - npm run start &
  - sleep 30
  - curl -Is localhost:3000 | head -n 1 | grep "OK"
  